name: flutter_local_notifications_extended
description: A cross platform plugin for displaying and scheduling local notifications for Flutter applications with the ability to customise for each platform.
version: 0.9.2
author: Michael Bui <michael@dexterx.dev>, Saleh Yassin <yass0016@gmail.com>
homepage: https://github.com/yass0016/flutter_local_notifications

dependencies:
  flutter:
    sdk: flutter
#  meta: ^1.7.0
  platform: ^3.0.2
#  path_provider: ^2.0.3
#  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.15
#  mockito: ^4.1.0

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.dexterous.flutterlocalnotifications
    pluginClass: FlutterLocalNotificationsPlugin

environment:
  sdk: '>=2.7.0 <3.0.0'
#   sdk: ">=2.0.0-dev.28.0 <3.0.0"
#   flutter: ">=1.5.0 <2.0.0"
